# Generated by Django 6.0.4 on 2026-05-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('image', models.URLField()),
                ('rating', models.FloatField(default=4.5)),
            ],
        ),
    ]
