# Generated by Django 6.0.4 on 2026-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('top_selling', 'Top Selling')], default='new_arrival', max_length=20),
        ),
    ]
