# Generated by Django 6.0.1 on 2026-05-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_related',
            field=models.BooleanField(default=False),
        ),
    ]
