# Generated by Django 6.0.1 on 2026-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_show_in_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('top_selling', 'Top Selling'), ('shop', 'Shop')], default='new_arrival', max_length=20),
        ),
    ]
