# Generated by Django 6.0.1 on 2026-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('top_selling', 'Top Selling'), ('shop', 'Shop'), ('T-Shirt', 'T-Shirt'), ('Shorts', 'Shorts'), ('Shirt', 'Shirt'), ('Hoodie', 'Hoodie'), ('Jeans', 'Jeans')], default='new_arrival', max_length=20),
        ),
    ]
