# Generated by Django 6.0.4 on 2026-05-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Red, Blue, White', max_length=50)),
                ('hex_code', models.CharField(help_text='Example: #F50606', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-Large', 'X-Large')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dress_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.dressstyle'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_category',
            field=models.CharField(choices=[('T-shirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Hoodie', 'Hoodie')], default='T-shirts', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('top_selling', 'Top Selling')], default='new_arrival', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='products.productcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='products.productsize'),
        ),
    ]
