# Generated by Django 6.0.4 on 2026-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcolor_productsize_product_dress_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('top_selling', 'Top Selling'), ('shop', 'Shop Only')], default='new_arrival', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_category',
            field=models.CharField(choices=[('T-shirts', 'T-shirts'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Hoodie', 'Hoodie'), ('Jackets', 'Jackets'), ('Dresses', 'Dresses'), ('Tops', 'Tops'), ('Activewear', 'Activewear'), ('Blazers', 'Blazers')], default='T-shirts', max_length=50),
        ),
    ]
