# Generated by Django 6.0.4 on 2026-05-14 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_review'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product'),
            preserve_default=False,
        ),
    ]
